# Setup
title:               Devendra Vyas's Blog
tagline:             
description:         Trivialise complex concepts
url:                 https://blog.vyas.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Devendra Vyas
  url:               https://vyas.dev
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
